---
gitlab_url: https://gitlab.com/

gitlab_runner_description: product-catalog-dev-runner

gitlab_runner_executor: docker

gitlab_runner_default_image: docker:27-cli

gitlab_runner_token: "{{ lookup('env', 'GITLAB_RUNNER_TOKEN') }}"

base_domain: example.com

nginx_sites:
  - name: catalog-api
    server_name: "catalog-api.{{ base_domain }}"
    upstream_host: 127.0.0.1
    upstream_port: 8082
  - name: catalog-grafana
    server_name: "catalog-grafana.{{ base_domain }}"
    upstream_host: 127.0.0.1
    upstream_port: 3000

certbot_email: admin@example.com
certbot_agree_tos: true
certbot_redirect_http_to_https: true
