---
- name: Configure GitLab Runner
  hosts: dev
  gather_facts: false
  become: true

  pre_tasks:
    - name: Validate GitLab Runner token
      ansible.builtin.assert:
        that:
          - gitlab_runner_token is defined
          - gitlab_runner_token | length > 0
        fail_msg: Environment variable GITLAB_RUNNER_TOKEN is required
      delegate_to: localhost
      become: false
      run_once: true

  roles:
    - role: nginx
    - role: certbot
    - role: gitlab_runner
